### ISSUE TITLE
tar: can't open './allure-2.18.1.tgz': No such file or directory

### ISSUE THREAD

**Issue by dimko** [PavanMudigonda/allure-html-reporter-aws-s3-website#1]
Hey thanks for this useful action.

The workflow is failing due to the following error:

> 2022-07-11 13:31:46 URL:https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.18.1/allure-commandline-2.18.1.tgz [19980996/19980996] -> "/tmp/allure-2.18.1.tgz" [1]
>   tar: can't open './allure-2.18.1.tgz': No such file or directory

the tar file seems to be used as **allure-$RELEASE.tgz** instead of **allure-commandline-$RELEASE.tgz** which is the download name

**Comment by PavanMudigondaTR** [comment]
@dimko I will fix in 30 mins. I know about this issue i fixed in my GH Pages Allure report.
